### ISSUE TITLE
Airplane mode issue 

### ISSUE THREAD

**Issue by gerigorila** [joelkanyi/KomposeCountryCodePicker#15]
_**Description:**_
When airplane mode is enabled on the device, the app crashes because it is unable to get the country code from the SIM card. The KomposeCountryCodePicker component does not have a default country code set, so it throws a NoSuchElementException when it tries to get the country code from the empty SIM card data.

**_Steps to reproduce:_**
Enable airplane mode on the device.
Open the app and navigate to the screen where the KomposeCountryCodePicker component is used.

**_Expected behavior:_**
The app should not crash when airplane mode is enabled. The KomposeCountryCodePicker component should either set a default country code or handle the case where there is no SIM card data available.

**_Actual behavior:_**
The app crashes with a NoSuchElementException.

**_Device info:_**
Google Pixel 2XL api level 30

**_Exception code:_**
```
19:32:36.680 FATAL EXCEPTION: main
             Process: com.time2staff.beta, PID: 17000
             java.util.NoSuchElementException: Collection contains no element matching the predicate.
             	at com.joelkanyi.jcomposecountrycodepicker.component.KomposeCountryCodePickerKt$KomposeCountryCodePicker$2.invoke(KomposeCountryCodePicker.kt:297)
             	at com.joelkanyi.jcomposecountrycodepicker.component.KomposeCountryCodePickerKt$KomposeCountryCodePicker$2.invoke(KomposeCountryCodePicker.kt:98)
             	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
             	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
             	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
             	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
             	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
             	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
             	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
             	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
```

**Comment by joelkanyi** [comment]
Thank you @gerigorila for the issue, let me investigate it

**Comment by joelkanyi** [comment]
Please update to 1.0.8 and confirm if the issue is fixed, also there is a parameter `defaultCountryCode = "tz"` that you can use to set your default country code.
